### ISSUE TITLE
Add getPiece() function to different file

### ISSUE THREAD

**Issue by SrNightmare09** [SrNightmare09/chess-fen-reader#1]
Add the `getPiece()` function to a different file.

**Comment by Univercee** [comment]
Hi! this is my first contribution. Are there any naming, styling or other requirements in addition to marked in CONTRIBUTING.md and CODE_OF_CONDUCT.md?

**Comment by voronov007** [comment]
Hi. I also would like to contribute to the project and fix the listed issue.

**Comment by SrNightmare09** [comment]
@voronov007 
Surely! I have assigned the issue to you. You can proceed to work on it.

**Comment by SrNightmare09** [comment]
@Univercee Not really. 
Some conventions you can follow are:
- naming variables with the pascalCase convention
- making different files for different files

Anything else will be told to be fixed once you open a PR and I review the code!

**Comment by voronov007** [comment]
Please review the MR. Thanks
