### ISSUE TITLE
Bug: On flipping the board all pieces turn to horses

### ISSUE THREAD

**Issue by AmitT98** [SrNightmare09/chess-fen-reader#10]
This video makes it clearer to understand

https://github.com/SrNightmare09/chess-fen-reader/assets/104303111/fe02549b-2ad8-4827-a193-598e73d0d77e

**Comment by AmitT98** [comment]
The issue is very similar to #8, I have fixed it and tested it. I will create PR once the owner approves and assigns the issue.

**Comment by SrNightmare09** [comment]
Sure @AmitT98 , I have assigned you to this issue! And thanks for bringing it up as well as fixing it! Your contributions are highly appreciated!
