### ISSUE TITLE
What do you mean by "Error handling upon invalid input"

### ISSUE THREAD

**Issue by Prashanth-Chandra** [SrNightmare09/chess-fen-reader#14]
Will something like this be sufficient?
![image](https://github.com/SrNightmare09/chess-fen-reader/assets/91191641/731cbdd2-0eb8-485e-a262-3af4b7af5a05)

And what are the possible invalid inputs

I made a function which checks errors regarding the number of pieces (like it will return false if there are more pieces than the max number of pieces and if any other character other than the standard FEN characters are inputted)

**Comment by SrNightmare09** [comment]
wow! this is more than sufficient! thank you for your dedication to this project!

**Comment by Prashanth-Chandra** [comment]
@SrNightmare09 Can you test the code once again to check if I missed any corner cases.

**Comment by SrNightmare09** [comment]
@Prashanth-Chandra please define what you mean by corner cases

**Comment by Prashanth-Chandra** [comment]
I mean any invalid input that I might have missed

**Comment by SrNightmare09** [comment]
@Prashanth-Chandra yes that is a case as well, another case which i could think of was -
- a side having no king
- a side having more than one king

**Comment by Prashanth-Chandra** [comment]
Will work on it
The second one has been taken care of

**Comment by SrNightmare09** [comment]
> Will work on it The second one has been taken care of



> Will work on it The second one has been taken care of

I dont know how to thank you for your dedication towards this project!

**Comment by Prashanth-Chandra** [comment]
Added checks for side having no king and position of pawns.

No need to thank me. I've always wanted to make a chess board using FEN but I lacked the front end capability to make it 😅.
