### ISSUE TITLE
fix: batch script opens file explorer window rather than browser

### ISSUE THREAD

**Issue by SrNightmare09** [SrNightmare09/chess-fen-reader#17]
the `start` command of the batch script file opens a new window of file explorer rather than of the browser

**Comment by AmitT98** [comment]
Can you describe the issue a bit more? Possibly with images/video.

**Comment by SrNightmare09** [comment]
> Can you describe the issue a bit more? Possibly with images/video.

well, if you check out the `build-script-test` branch, I am aiming to create a batch file which a person can download to easily check out this project. I have been successful in cloning the repository in the person's system, but I cannot get the browser to open at a certain file directory.

example: if after cloning the repo, the project gets added to a certain system directory, the person can view the website by directly typing in the directory address for the index.html file in their browser. however, when i try using the `start` command to open the browser with the file link, the system opens file explorer instead of the browser.

I will make sure to follow up this comment with a video soon.

**Comment by AmitT98** [comment]
Okay, I can start working on this.

**Comment by Prashanth-Chandra** [comment]
@SrNightmare09 Did you mean that it should work like this?

https://github.com/SrNightmare09/chess-fen-reader/assets/91191641/768a3f8a-adc3-42cc-b086-fa02dd85fd22

My current code clones the repo and opens the index.html file

**Comment by AmitT98** [comment]
I think @Prashanth-Chandra code works fine. Once the repository is clone user can simply open .html file to load the FEN-reader in the default browser.

**Comment by Prashanth-Chandra** [comment]
> I think @Prashanth-Chandra code works fine. Once the repository is cloned user can simply open .html file to load the FEN-reader in the default browser. Your thoughts @SrNightmare09 ?

I actually did not get the issue, I assumed that this was the issue and worked on it 😅

**Comment by SrNightmare09** [comment]
> 

Yes, his code works perfectly! Though I am not really sure what was wrong with my script.

**Comment by Prashanth-Chandra** [comment]
@SrNightmare09  In the code you write did you add '@' before "REM GET DIRECTORY" and "REM GET PARENT DIRS"

**Comment by SrNightmare09** [comment]
@Prashanth-Chandra oh i see, how stupid of me haha.
