### ISSUE TITLE
Feature Addition: Numbers and Letters on side of board

### ISSUE THREAD

**Issue by AmitT98** [SrNightmare09/chess-fen-reader#20]
I have added the numbers and alphabets by modifying the index.html and style.css file. Below is how is looks,
![image](https://github.com/SrNightmare09/chess-fen-reader/assets/104303111/145a9bc9-396b-48be-a7f4-0d481901d51c)
Let me know if this is good enough so that I can raise a PR.

**Comment by SrNightmare09** [comment]
> I have added the numbers and alphabets by modifying the index.html and style.css file. Below is how is looks, ![image](https://user-images.githubusercontent.com/104303111/250393447-145a9bc9-396b-48be-a7f4-0d481901d51c.png) Let me know if this is good enough so that I can raise a PR.

Looks great! Here are a few more suggestions:
- the buttons should be below the letters
- the numbers should be upright
- the numbers on the white side start with 1
- make sure that the numbers and letters adjust upon flipping the board.

**Comment by AmitT98** [comment]
I made the changes. Take a look, 

https://github.com/SrNightmare09/chess-fen-reader/assets/104303111/4bb6dab2-a992-4302-be00-d00ed886b063

**Comment by SrNightmare09** [comment]
@AmitT98 looks great! but I would like to see the letters having gap between the board like the numbers do, and if possible, it would be nice to see each letter aligned to the center of the cell (like the numbers). if you feel like it is not required, feel free to tell me and I have be happy to receive a PR anyway! :)

**Comment by AmitT98** [comment]
Hi @SrNightmare09 I have made centre align change as well in my local repo. However the current state of code in master is somewhat not rendering properly. Can you you check it once at your end. For me it shows like this.
![image](https://github.com/SrNightmare09/chess-fen-reader/assets/104303111/cd6c4af6-2dc3-40e0-bcd6-e5fa4f2a0459)

**Comment by SrNightmare09** [comment]
@AmitT98 The code works perfectly fine on my end.

**Comment by AmitT98** [comment]
Yes now it now renders correctly for me as well. By the way, I made the necessary changes and raised a PR.
