### ISSUE TITLE
ci: checks failing - 'jest' undefined

### ISSUE THREAD

**Issue by SrNightmare09** [SrNightmare09/chess-fen-reader#35]
![image](https://github.com/SrNightmare09/chess-fen-reader/assets/73314216/f6e36b2d-3235-4738-bb57-4bbee2ad0a49)

**Comment by AmitT98** [comment]
Hi @SrNightmare09 do you want me to take up this issue?

**Comment by SrNightmare09** [comment]
@AmitT98 Do you have any idea what might be causing this error on the nodejs ci? If you do, I will assign the issue to you.

**Comment by AmitT98** [comment]
For me the error does't occur, is it windows specific only? 
<img width="808" alt="image" src="https://github.com/SrNightmare09/chess-fen-reader/assets/104303111/c915c549-60a1-4463-9b37-1b4ac1c2ebae">

**Comment by SrNightmare09** [comment]
@AmitT98 This is not an issue we are facing with the project but rather with the Github NodeJS workflow. You can view that [here](https://github.com/SrNightmare09/chess-fen-reader/actions).

I am currently trying to fix it by removing tests of the project with Node 14x. I think that might help.

**Comment by SrNightmare09** [comment]
Closed by [`148b044`](https://github.com/SrNightmare09/chess-fen-reader/commit/148b044c8e40015fb600bbda00b1acc40fbfc95f)
