### ISSUE TITLE
feat: allow for user to flip board

### ISSUE THREAD

**Issue by SrNightmare09** [SrNightmare09/chess-fen-reader#5]
probably can be done by reversing array of each rank and then reversing rank order

**Comment by Prashanth-Chandra** [comment]
@SrNightmare09 Can you assign this to me?
I have coded it and its working fine

**Comment by SrNightmare09** [comment]
@Prashanth-Chandra wow, that's great to here. I have assigned you to this issue.

**Comment by Prashanth-Chandra** [comment]
@SrNightmare09 Can you please close this issue.
