### ISSUE TITLE
fix: when new piece theme is selected, board arrangement is back to default

### ISSUE THREAD

**Issue by SrNightmare09** [SrNightmare09/chess-fen-reader#8]
Need to implement a way to call the generateBoard() function upon change of value of dropdown such that the fenString paramter is not required, or remains the same.

**Comment by AmitT98** [comment]
Hi @SrNightmare09 I would like to work on issue. Please can you assign it to me.

**Comment by SrNightmare09** [comment]
> Hi @SrNightmare09 I would like to work on issue. Please can you assign it to me.

Sure! good luck. I have assigned you to this issue.
